=== RiccardoRunci/Progetto_00/app/src/main/resources/Oggetti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--File xsd che valida tutti gli Oggetti(Armi e Medikit) contenuti dentro il file Oggetti.xml.
	Differentemente da come ho fatto con Maghi.xml (che conteneva solo i Maghi, senza Guerrieri)
	I Guerrieri stavano in un altro file .json!
	Dato che DTD lo ho usato per Maghi.xml, Qui vorrei utilizzare gli XSD per validare questo file Oggetti.xml.-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Oggetti">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <!--Se uso choice, devo togliere il sequence che stava qui!-->
                <xs:element name="Arma" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nomeOggetto" type="xs:string"/>
                            <xs:element name="puntiDannoPiu" type="xs:positiveInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Medikit" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nomeOggetto" type="xs:string"/>
                            <xs:element name="puntiVitaRistabiliti" type="xs:positiveInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <!--qui c'era la chiusura del sequence che ho tolto, perchè ho messo choice!-->
            </xs:choice> <!-- Con xs:choice 1<x>max posso fare come ((Arma|Medikit)+) -->
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RiccardoRunci/Progetto_00/app/src/main/resources/Oggetti.xml
<!--File xml che contiene una lista di Medikit e Armi.
    Questo file ha il suo validatore xsd (sempre dentro la cartella Resource, Oggetti.xsd).-->
<Oggetti  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:noNamespaceSchemaLocation="Oggetti.xsd">

<Medikit>
	<nomeOggetto>Paracetamolo generico</nomeOggetto>
	<puntiVitaRistabiliti>50</puntiVitaRistabiliti>
</Medikit>
<Medikit>
	<nomeOggetto>Bayer</nomeOggetto>
	<puntiVitaRistabiliti>50</puntiVitaRistabiliti>
</Medikit>
<Medikit>
	<nomeOggetto>Pfizer</nomeOggetto>
	<puntiVitaRistabiliti>50</puntiVitaRistabiliti>
</Medikit>
<Medikit>
	<nomeOggetto>Moderna</nomeOggetto>
	<puntiVitaRistabiliti>50</puntiVitaRistabiliti>
</Medikit>
<Medikit>
	<nomeOggetto>Angelini</nomeOggetto>
	<puntiVitaRistabiliti>50</puntiVitaRistabiliti>
</Medikit>
<Medikit>
	<nomeOggetto>Roche</nomeOggetto>
	<puntiVitaRistabiliti>50</puntiVitaRistabiliti>
</Medikit>
<Medikit>
	<nomeOggetto>Sanofi</nomeOggetto>
	<puntiVitaRistabiliti>50</puntiVitaRistabiliti>
</Medikit>
<Medikit>
	<nomeOggetto>AstraZeneca</nomeOggetto>
	<puntiVitaRistabiliti>50</puntiVitaRistabiliti>
</Medikit>
<Medikit>
	<nomeOggetto>Ibuprofene Generico</nomeOggetto>
	<puntiVitaRistabiliti>50</puntiVitaRistabiliti>
</Medikit>
<Medikit>
	<nomeOggetto>Imodium</nomeOggetto>
	<puntiVitaRistabiliti>50</puntiVitaRistabiliti>
</Medikit>
<Medikit>
	<nomeOggetto>Enterogermina</nomeOggetto>
	<puntiVitaRistabiliti>50</puntiVitaRistabiliti>
</Medikit>


<Arma>
	<nomeOggetto>CANNONE</nomeOggetto>
	<puntiDannoPiu>100</puntiDannoPiu>
</Arma>
<Arma>
	<nomeOggetto>Beretta</nomeOggetto>
	<puntiDannoPiu>60</puntiDannoPiu>
</Arma>
<Arma>
	<nomeOggetto>Glock</nomeOggetto>
	<puntiDannoPiu>60</puntiDannoPiu>
</Arma>
<Arma>
	<nomeOggetto>SmithWesson</nomeOggetto>
	<puntiDannoPiu>80</puntiDannoPiu>
</Arma>
<Arma>
	<nomeOggetto>Colt</nomeOggetto>
	<puntiDannoPiu>90</puntiDannoPiu>
</Arma>
<Arma>
	<nomeOggetto>Balestra</nomeOggetto>
	<puntiDannoPiu>45</puntiDannoPiu>
</Arma>
<Arma>
	<nomeOggetto>Coltello</nomeOggetto>
	<puntiDannoPiu>30</puntiDannoPiu>
</Arma>

<Arma>
	<nomeOggetto>Fionda</nomeOggetto>
	<puntiDannoPiu>15</puntiDannoPiu>
</Arma>
<Arma>
	<nomeOggetto>Bazzuka</nomeOggetto>
	<puntiDannoPiu>500</puntiDannoPiu>
</Arma>
<Arma>
	<nomeOggetto>BFG90000</nomeOggetto>
	<puntiDannoPiu>9000</puntiDannoPiu>
</Arma>
<Arma>
	<nomeOggetto>Doppietta</nomeOggetto>
	<puntiDannoPiu>95</puntiDannoPiu>
</Arma>
</Oggetti>
